# Generated by Django 5.2.5 on 2025-09-15 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('title_eng', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_display', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='StorymodeMoment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='storymode.story')),
            ],
            options={
                'db_table': 'storymode_moment',
            },
        ),
        migrations.CreateModel(
            name='StorymodeChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('GOOD', 'Good'), ('NEUTRAL', 'Neutral'), ('BAD', 'Bad'), ('ENDING_GOOD', 'Ending_good'), ('ENDING_BAD', 'Ending_bad')], max_length=50)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='storymode.storymodemoment')),
                ('next_moment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_choices', to='storymode.storymodemoment')),
            ],
            options={
                'db_table': 'storymode_choice',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='start_moment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_of_stories', to='storymode.storymodemoment'),
        ),
        migrations.CreateModel(
            name='StorymodeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('play', 'Playing'), ('finish', 'Finished')], default='play', max_length=20)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_moment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storymode.storymodemoment')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_storymode_session', to='storymode.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_storymode_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storymode_session',
            },
        ),
    ]
